[graph]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[advisories]
unmaintained = "workspace"
ignore = []

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
]
exceptions = [
    { allow = ["CC0-1.0"], crate = "notify@8.2.0" },
    { allow = ["CDLA-Permissive-2.0"], crate = "webpki-roots@1.0.8" },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
