//! Purpose: verify source-update behavior with local Git fixtures.
//! Owns: discovery, dirty-change preservation, and trusted-origin rejection.
//! Must not: contact a remote, alter the real checkout, or invoke the full updater.
//! Invariants: each repository is unique, temporary, and removed after the assertion.

use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

use super::*;

fn fixture() -> PathBuf {
    let suffix = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let root = std::env::temp_dir().join(format!(
        "catomic-source-discovery-test-{}-{suffix}",
        std::process::id()
    ));
    fs::create_dir(&root).unwrap();
    for args in [
        vec!["init", "-b", "master"],
        vec!["config", "user.name", "Catomic Test"],
        vec!["config", "user.email", "catomic@example.invalid"],
    ] {
        let status = Command::new("git")
            .current_dir(&root)
            .args(args)
            .status()
            .unwrap();
        assert!(status.success());
    }
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"catomic\"\nversion = \"0.0.0\"\n",
    )
    .unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = \"catomic\"\nversion = \"0.0.0\"\n",
    )
    .unwrap();
    fs::create_dir(root.join("src")).unwrap();
    fs::write(root.join("src/main.rs"), "fn main() {}\n").unwrap();
    assert!(Command::new("git")
        .current_dir(&root)
        .args(["add", "."])
        .status()
        .unwrap()
        .success());
    assert!(Command::new("git")
        .current_dir(&root)
        .args(["commit", "-m", "fixture"])
        .status()
        .unwrap()
        .success());
    assert!(Command::new("git")
        .current_dir(&root)
        .args(["remote", "add", "origin", OFFICIAL_REMOTE])
        .status()
        .unwrap()
        .success());
    root
}

fn git(root: &Path, args: &[&str]) {
    assert!(git_output(root, args).unwrap().status.success());
}

#[test]
fn discovery_detects_clean_and_dirty_official_source_checkouts() {
    let root = fixture();
    git(&root, &["branch", "-m", "main"]);
    let clean = discover_at(&root).unwrap();
    assert_eq!(clean.branch, "main");
    assert!(!clean.dirty);

    fs::write(root.join("local-notes"), b"preserve me").unwrap();
    let dirty = discover_at(&root).unwrap();
    assert!(dirty.dirty);

    fs::remove_dir_all(root).unwrap();
}

#[test]
fn remote_policy_rejects_lookalikes() {
    assert!(is_official_remote(OFFICIAL_REMOTE));
    assert!(is_official_remote("git@github.com:maelguimet/catomic.git"));
    assert!(!is_official_remote(
        "https://github.com/attacker/maelguimet-catomic.git"
    ));
}

#[test]
fn missing_checkout_selects_controlled_path_install() {
    let root = fixture();
    assert!(discover_path(&root.join("missing")).unwrap().is_none());

    let revision = "71f3cbd98484e5bb9be921d63ff1ebf9394ecafe";
    let install_root = root.join("cargo-home");
    let checkout = root.join("checkout");
    let target = root.join("target");
    let command = cargo_install_command(&checkout, &install_root, &target, revision);
    let args: Vec<_> = command
        .get_args()
        .map(|argument| argument.to_str().unwrap())
        .collect();
    assert_eq!(
        args,
        [
            "install",
            "--path",
            checkout.to_str().unwrap(),
            "--locked",
            "--force",
            "--root",
            install_root.to_str().unwrap(),
            "--target-dir",
            target.to_str().unwrap(),
        ]
    );
    let environment = command
        .get_envs()
        .map(|(name, value)| {
            (
                name.to_str().unwrap(),
                value.and_then(|value| value.to_str()),
            )
        })
        .collect::<Vec<_>>();
    assert!(environment.contains(&("CATOMIC_SOURCE_DIR", Some(""))));
    assert!(environment.contains(&("CATOMIC_BUILD_COMMIT", Some(revision))));
    assert!(environment.contains(&("CATOMIC_BUILD_DIRTY", Some("0"))));
    fs::remove_dir_all(root).unwrap();
}

#[test]
fn implicit_cargo_git_checkout_uses_cargo_install_again() {
    let manifest = Path::new("/home/test/.cargo/git/checkouts/catomic-123456/revision");
    assert!(is_cargo_git_checkout(manifest));
    assert_eq!(retained_source_path(None, manifest), None);

    assert_eq!(
        retained_source_path(Some("/home/test/src/catomic"), manifest),
        Some(Path::new("/home/test/src/catomic"))
    );
}

#[test]
fn cargo_install_targets_the_invoked_binary_root() {
    assert_eq!(
        cargo_install_root(Path::new("/home/test/.cargo/bin/catomic")).unwrap(),
        Path::new("/home/test/.cargo")
    );
    assert!(cargo_install_root(Path::new("/home/test/catomic")).is_err());
}

#[cfg(target_os = "linux")]
#[test]
fn installed_version_verification_requires_the_exact_revision() {
    use std::os::unix::fs::PermissionsExt;

    let root = std::env::temp_dir().join(format!(
        "catomic-installed-version-test-{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir(&root).unwrap();
    let executable = root.join("catomic");
    fs::write(
        &executable,
        "#!/bin/sh\nprintf '%s\\n' 'catomic 1.2.3 (commit 71f3cbd98484)'\n",
    )
    .unwrap();
    fs::set_permissions(&executable, fs::Permissions::from_mode(0o700)).unwrap();

    let revision = "71f3cbd98484e5bb9be921d63ff1ebf9394ecafe";
    verify_installed_version(&executable, "1.2.3", revision).unwrap();
    let error = verify_installed_version(
        &executable,
        "1.2.3",
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    )
    .unwrap_err();
    assert_eq!(error.exit_code(), EXIT_INSTALL);
    assert!(error.to_string().contains("update not confirmed"));

    fs::remove_dir_all(root).unwrap();
}

#[test]
fn source_update_builds_without_spawning_cargo_test() {
    assert_eq!(RELEASE_BUILD_ARGS, ["build", "--release", "--locked"]);
    assert!(!RELEASE_BUILD_ARGS.contains(&"test"));
}

#[test]
fn retained_checkout_workspace_cleans_after_successful_local_build() {
    let root = fixture();
    let sha = git_text(&root, &["rev-parse", "HEAD"]).unwrap();
    let temporary_parent = root.with_extension("successful-workspace");
    let cargo_home = root.with_extension("successful-cargo-home");
    fs::create_dir(&temporary_parent).unwrap();
    fs::create_dir(&cargo_home).unwrap();
    let workspace = UpdateWorkspace::create_worktree_in(&temporary_parent, &root, &sha).unwrap();
    let workspace_root = workspace.root().to_path_buf();

    with_workspace(workspace, |workspace| {
        let mut command = cargo_with_source_command(
            &workspace.checkout,
            &["build", "--locked", "--offline"],
            &root,
            &sha,
            &workspace.target,
        );
        command.env("CARGO_HOME", &cargo_home);
        run_cargo(&mut command)
    })
    .unwrap();

    assert!(!workspace_root.exists());
    fs::remove_dir_all(root).unwrap();
    fs::remove_dir_all(temporary_parent).unwrap();
    fs::remove_dir_all(cargo_home).unwrap();
}

#[test]
fn standalone_checkout_workspace_cleans_after_failed_local_build() {
    let root = fixture();
    let sha = git_text(&root, &["rev-parse", "HEAD"]).unwrap();
    let temporary_parent = root.with_extension("failed-workspace");
    let cargo_home = root.with_extension("failed-cargo-home");
    fs::create_dir(&temporary_parent).unwrap();
    fs::create_dir(&cargo_home).unwrap();
    let remote = root.to_string_lossy().into_owned();
    let workspace =
        UpdateWorkspace::clone_revision_in(&temporary_parent, &remote, "master", &sha).unwrap();
    let workspace_root = workspace.root().to_path_buf();
    let install_root = root.with_extension("failed-install-root");

    let error = with_workspace(workspace, |workspace| {
        fs::remove_file(workspace.checkout.join("src/main.rs")).unwrap();
        let mut command =
            cargo_install_command(&workspace.checkout, &install_root, &workspace.target, &sha);
        command.env("CARGO_HOME", &cargo_home);
        command.env("CARGO_NET_OFFLINE", "true");
        run_cargo(&mut command)
    })
    .unwrap_err();

    assert_eq!(error.exit_code(), EXIT_BUILD);
    assert!(!workspace_root.exists());
    fs::remove_dir_all(root).unwrap();
    fs::remove_dir_all(temporary_parent).unwrap();
    fs::remove_dir_all(cargo_home).unwrap();
    if install_root.exists() {
        fs::remove_dir_all(install_root).unwrap();
    }
}

#[test]
fn source_changes_survive_update_and_restore_staged_state() {
    let root = fixture();
    fs::write(root.join("Cargo.toml"), "previous stash\n").unwrap();
    git(&root, &["stash", "push", "--message", "previous stash"]);
    let previous = git_text(&root, &["rev-parse", "--verify", "refs/stash"]).unwrap();
    fs::write(root.join("Cargo.toml"), "local change\n").unwrap();
    git(&root, &["add", "Cargo.toml"]);
    fs::write(root.join("local-notes"), "untracked change\n").unwrap();

    let stashed = stash_changes(&root).unwrap().unwrap();
    assert!(git_text(&root, &["status", "--porcelain=v1"])
        .unwrap()
        .is_empty());
    fs::write(root.join("Cargo.toml"), "concurrent stash\n").unwrap();
    git(&root, &["stash", "push", "--message", "concurrent stash"]);
    let concurrent = git_text(&root, &["rev-parse", "--verify", "refs/stash"]).unwrap();
    fs::write(root.join("upstream"), "new upstream file\n").unwrap();
    git(&root, &["add", "upstream"]);
    git(&root, &["commit", "-m", "upstream update"]);

    restore_changes(&root, Some(&stashed)).unwrap();

    assert_eq!(
        fs::read_to_string(root.join("Cargo.toml")).unwrap(),
        "local change\n"
    );
    assert_eq!(
        fs::read_to_string(root.join("local-notes")).unwrap(),
        "untracked change\n"
    );
    assert_eq!(
        git_text(&root, &["diff", "--cached", "--name-only"]).unwrap(),
        "Cargo.toml"
    );
    assert_eq!(
        git_text(&root, &["stash", "list", "--format=%H"]).unwrap(),
        format!("{concurrent}\n{previous}")
    );
    fs::remove_dir_all(root).unwrap();
}

#[test]
fn restore_conflict_keeps_exact_updater_stash_recoverable() {
    let root = fixture();
    fs::write(root.join("Cargo.toml"), "local change\n").unwrap();
    git(&root, &["add", "Cargo.toml"]);
    let stash = stash_changes(&root).unwrap().unwrap();

    fs::write(root.join("Cargo.toml"), "upstream change\n").unwrap();
    git(&root, &["add", "Cargo.toml"]);
    git(&root, &["commit", "-m", "upstream update"]);

    let error = restore_changes(&root, Some(&stash)).unwrap_err();
    assert!(error.contains(short_sha(&stash)));
    assert!(git_text(&root, &["stash", "list", "--format=%H"])
        .unwrap()
        .lines()
        .any(|candidate| candidate == stash));
    fs::remove_dir_all(root).unwrap();
}
